<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\vagasModel;


class vagasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        vagasModel::create([
            'id_vagas' => 1,
            'email_vaga' => 'cleitinGrau@gmail.com',
            'titulo_vagas' => 'Desenvolvedor PHP Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 3000,
            'fim_salario_vagas' => 5000,
            'local_vagas' => 'São Paulo - SP',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'PHP',
            'estado_vaga' => 'SP',
            'pausado' => false,
            'fk_usuario_id' => 1,
        ]);

        vagasModel::create([
            'id_vagas' => 2,
            'email_vaga' => 'maria.silva@example.com',
            'titulo_vagas' => 'Desenvolvedor Python Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 6000,
            'fim_salario_vagas' => 9000,
            'local_vagas' => 'Rio de Janeiro - RJ',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'PY',
            'estado_vaga' => 'RJ',
            'pausado' => false,
            'fk_usuario_id' => 2,
        ]);

        vagasModel::create([
            'id_vagas' => 3, 
            'email_vaga' => 'joao.pereira@example.com',
            'titulo_vagas' => 'Engenheiro de Dados Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 12000,
            'fim_salario_vagas' => 15000,
            'local_vagas' => 'Curitiba - PR',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'SQL',
            'estado_vaga' => 'PR',
            'pausado' => false,
            'fk_usuario_id' => 3,
        ]);

        vagasModel::create([
            'id_vagas' => 4,
            'email_vaga' => 'ana.costa@example.com',
            'titulo_vagas' => 'Desenvolvedor Java Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 4000,
            'fim_salario_vagas' => 6000,
            'local_vagas' => 'Belo Horizonte - MG',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'JV',
            'estado_vaga' => 'MG',
            'pausado' => false,
            'fk_usuario_id' => 4,
        ]);

        vagasModel::create([
            'id_vagas' => 5,
            'email_vaga' => 'lucas.souza@example.com',
            'titulo_vagas' => 'Desenvolvedor Front-End Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 7000,
            'fim_salario_vagas' => 9000,
            'local_vagas' => 'Fortaleza - CE',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'JS',
            'estado_vaga' => 'CE',
            'pausado' => false,
            'fk_usuario_id' => 5,
        ]);

        vagasModel::create([
            'id_vagas' => 6,
            'email_vaga' => 'beatriz.lima@example.com',
            'titulo_vagas' => 'Desenvolvedor C++ Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 11000,
            'fim_salario_vagas' => 14000,
            'local_vagas' => 'Brasília - DF',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'CPP',
            'estado_vaga' => 'DF',
            'pausado' => false,
            'fk_usuario_id' => 6,
        ]);

        vagasModel::create([
            'id_vagas' => 7,
            'email_vaga' => 'pedro.rocha@example.com',
            'titulo_vagas' => 'Administrador de Banco de Dados',
            'descrição' => "null",
            'inicio_salario_vagas' => 8000,
            'fim_salario_vagas' => 10000,
            'local_vagas' => 'Salvador - BA',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'PSQL',
            'estado_vaga' => 'BA',
            'pausado' => false,
            'fk_usuario_id' => 7,
        ]);

        vagasModel::create([
            'id_vagas' => 8,
            'email_vaga' => 'clara.martins@example.com',
            'titulo_vagas' => 'Desenvolvedor GoLang Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 5000,
            'fim_salario_vagas' => 7000,
            'local_vagas' => 'Florianópolis - SC',
            'tipo_vaga' => 'FL',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'GO',
            'estado_vaga' => 'SC',
            'pausado' => false,
            'fk_usuario_id' => 8,
        ]);

        vagasModel::create([
            'id_vagas' => 9,
            'email_vaga' => 'gustavo.alves@example.com',
            'titulo_vagas' => 'Desenvolvedor Kotlin Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 13000,
            'fim_salario_vagas' => 16000,
            'local_vagas' => 'Porto Alegre - RS',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'KT',
            'estado_vaga' => 'RS',
            'pausado' => false,
            'fk_usuario_id' => 9,
        ]);

        vagasModel::create([
            'id_vagas' => 10, 
            'email_vaga' => 'fernanda.souza@example.com',
            'titulo_vagas' => 'Desenvolvedor C# Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9000,
            'fim_salario_vagas' => 11000,
            'local_vagas' => 'Manaus - AM',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'CS',
            'estado_vaga' => 'AM',
            'pausado' => false,
            'fk_usuario_id' => 10,
        ]);
        vagasModel::create([
            'id_vagas' => 11,
            'email_vaga' => 'rafael.ferreira@example.com',
            'titulo_vagas' => 'Desenvolvedor Ruby Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 12000,
            'fim_salario_vagas' => 15000,
            'local_vagas' => 'Recife - PE',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'RB',
            'estado_vaga' => 'PE',
            'pausado' => false,
            'fk_usuario_id' => 11,
        ]);

        vagasModel::create([
            'id_vagas' => 12,
            'email_vaga' => 'carla.santos@example.com',
            'titulo_vagas' => 'Desenvolvedor Swift Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 3500,
            'fim_salario_vagas' => 5500,
            'local_vagas' => 'Campinas - SP',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'SW',
            'estado_vaga' => 'SP',
            'pausado' => false,
            'fk_usuario_id' => 12,
        ]);

        vagasModel::create([
            'id_vagas' => 13,
            'email_vaga' => 'diego.oliveira@example.com',
            'titulo_vagas' => 'Desenvolvedor Rust Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 8000,
            'fim_salario_vagas' => 10000,
            'local_vagas' => 'São Luís - MA',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'RS',
            'estado_vaga' => 'MA',
            'pausado' => false,
            'fk_usuario_id' => 13,
        ]);

        vagasModel::create([
            'id_vagas' => 14,
            'email_vaga' => 'fernanda.costa@example.com',
            'titulo_vagas' => 'Engenheiro de Machine Learning Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 14000,
            'fim_salario_vagas' => 18000,
            'local_vagas' => 'Goiânia - GO',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'ML',
            'estado_vaga' => 'GO',
            'pausado' => false,
            'fk_usuario_id' => 14,
        ]);

        vagasModel::create([
            'id_vagas' => 15,
            'email_vaga' => 'juliana.lima@example.com',
            'titulo_vagas' => 'Desenvolvedor SQL Server Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9000,
            'fim_salario_vagas' => 12000,
            'local_vagas' => 'Natal - RN',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'SQLS',
            'estado_vaga' => 'RN',
            'pausado' => false,
            'fk_usuario_id' => 15,
        ]);

        vagasModel::create([
            'id_vagas' => 16,
            'email_vaga' => 'gabriel.souza@example.com',
            'titulo_vagas' => 'Desenvolvedor Lua Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 4000,
            'fim_salario_vagas' => 6000,
            'local_vagas' => 'Belém - PA',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'LUA',
            'estado_vaga' => 'PA',
            'pausado' => false,
            'fk_usuario_id' => 16,
        ]);

        vagasModel::create([
            'id_vagas' => 17,
            'email_vaga' => 'lucas.oliveira@example.com',
            'titulo_vagas' => 'Desenvolvedor Typescript Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 8500,
            'fim_salario_vagas' => 10500,
            'local_vagas' => 'Teresina - PI',
            'tipo_vaga' => 'FL',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'TS',
            'estado_vaga' => 'PI',
            'pausado' => false,
            'fk_usuario_id' => 17,
        ]);

        vagasModel::create([
            'id_vagas' => 18,
            'email_vaga' => 'renata.almeida@example.com',
            'titulo_vagas' => 'Desenvolvedor Kotlin Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 4500,
            'fim_salario_vagas' => 6500,
            'local_vagas' => 'caxias  - RJ',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'KT',
            'estado_vaga' => 'RJ',
            'pausado' => false,
            'fk_usuario_id' => 18,
        ]);

        vagasModel::create([
            'id_vagas' => 19,
            'email_vaga' => 'marcos.teixeira@example.com',
            'titulo_vagas' => 'Desenvolvedor Dart Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 7500,
            'fim_salario_vagas' => 9500,
            'local_vagas' => 'João Pessoa - PB',
            'tipo_vaga' => 'FL',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'DT',
            'estado_vaga' => 'PB',
            'pausado' => false,
            'fk_usuario_id' => 19,
        ]);

        vagasModel::create([
            'id_vagas' => 20,
            'email_vaga' => 'paula.goncalves@example.com',
            'titulo_vagas' => 'Administrador de Banco de Dados Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9500,
            'fim_salario_vagas' => 11500,
            'local_vagas' => 'Aracaju - SE',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'MDB',
            'estado_vaga' => 'SE',
            'pausado' => false,
            'fk_usuario_id' => 20,
        ]);

        vagasModel::create([
            'id_vagas' => 21,
            'email_vaga' => 'thiago.andrade@example.com',
            'titulo_vagas' => 'Desenvolvedor Scala Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 4000,
            'fim_salario_vagas' => 5500,
            'local_vagas' => 'Vitória - ES',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'SC',
            'estado_vaga' => 'ES',
            'pausado' => false,
            'fk_usuario_id' => 21,
        ]);

        vagasModel::create([
            'id_vagas' => 22,
            'email_vaga' => 'amanda.martins@example.com',
            'titulo_vagas' => 'Desenvolvedor C Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 10000,
            'fim_salario_vagas' => 13000,
            'local_vagas' => 'Campo Grande - MS',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'C',
            'estado_vaga' => 'MS',
            'pausado' => false,
            'fk_usuario_id' => 22,
        ]);

        vagasModel::create([
            'id_vagas' => 23,
            'email_vaga' => 'carlos.lima@example.com',
            'titulo_vagas' => 'Desenvolvedor MySQL Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 8000,
            'fim_salario_vagas' => 10000,
            'local_vagas' => 'Porto Velho - RO',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'MYSQL',
            'estado_vaga' => 'RO',
            'pausado' => false,
            'fk_usuario_id' => 23,
        ]);

        vagasModel::create([
            'id_vagas' => 24,
            'email_vaga' => 'lara.souza@example.com',
            'titulo_vagas' => 'Desenvolvedor Python Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 12000,
            'fim_salario_vagas' => 15000,
            'local_vagas' => 'Maceió - AL',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'PY',
            'estado_vaga' => 'AL',
            'pausado' => false,
            'fk_usuario_id' => 24,
        ]);

        vagasModel::create([
            'id_vagas' => 25,
            'email_vaga' => 'bruno.nascimento@example.com',
            'titulo_vagas' => 'Desenvolvedor PHP Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 4500,
            'fim_salario_vagas' => 6000,
            'local_vagas' => 'Boa Vista - RR',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'PHP',
            'estado_vaga' => 'RR',
            'pausado' => false,
            'fk_usuario_id' => 25,
        ]);
        vagasModel::create([
            'id_vagas' => 26,
            'email_vaga' => 'juliana.cardoso@example.com',
            'titulo_vagas' => 'Engenheiro de Dados Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9500,
            'fim_salario_vagas' => 12000,
            'local_vagas' => 'Palmas - TO',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'R',
            'estado_vaga' => 'TO',
            'pausado' => false,
            'fk_usuario_id' => 26,
        ]);

        vagasModel::create([
            'id_vagas' => 27,
            'email_vaga' => 'rodrigo.ferreira@example.com',
            'titulo_vagas' => 'Desenvolvedor Node.js Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 5000,
            'fim_salario_vagas' => 7000,
            'local_vagas' => 'Porto Alegre - RS',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'NODE',
            'estado_vaga' => 'RS',
            'pausado' => false,
            'fk_usuario_id' => 27,
        ]);

        vagasModel::create([
            'id_vagas' => 28,
            'email_vaga' => 'mariana.gomes@example.com',
            'titulo_vagas' => 'Desenvolvedor Flutter Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 8000,
            'fim_salario_vagas' => 10000,
            'local_vagas' => 'Florianópolis - SC',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'FLT',
            'estado_vaga' => 'SC',
            'pausado' => false,
            'fk_usuario_id' => 28,
        ]);

        vagasModel::create([
            'id_vagas' => 29,
            'email_vaga' => 'felipe.azevedo@example.com',
            'titulo_vagas' => 'Desenvolvedor Go Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 13000,
            'fim_salario_vagas' => 16000,
            'local_vagas' => 'Manaus - AM',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'GO',
            'estado_vaga' => 'AM',
            'pausado' => false,
            'fk_usuario_id' => 29,
        ]);

        vagasModel::create([
            'id_vagas' => 30,
            'email_vaga' => 'vanessa.moura@example.com',
            'titulo_vagas' => 'DevOps Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 10000,
            'fim_salario_vagas' => 13000,
            'local_vagas' => 'Curitiba - PR',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'DEVOPS',
            'estado_vaga' => 'PR',
            'pausado' => false,
            'fk_usuario_id' => 30,
        ]);

        vagasModel::create([
            'id_vagas' => 31,
            'email_vaga' => 'cleitinGrau@gmail.com',
            'titulo_vagas' => 'Engenheiro de Software Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 14000,
            'fim_salario_vagas' => 17000,
            'local_vagas' => 'Cuiabá - MT',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'CS',
            'estado_vaga' => 'MT',
            'pausado' => false,
            'fk_usuario_id' => 1,
        ]);

        vagasModel::create([
            'id_vagas' => 32,
            'email_vaga' => 'maria.silva@example.com',
            'titulo_vagas' => 'Desenvolvedor C++ Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 5000,
            'fim_salario_vagas' => 7000,
            'local_vagas' => 'Fortaleza - CE',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'CPP',
            'estado_vaga' => 'CE',
            'pausado' => false,
            'fk_usuario_id' => 2,
        ]);

        vagasModel::create([
            'id_vagas' => 33,
            'email_vaga' => 'joao.pereira@example.com',
            'titulo_vagas' => 'Desenvolvedor Backend Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 8500,
            'fim_salario_vagas' => 11000,
            'local_vagas' => 'Rio Branco - AC',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'JS',
            'estado_vaga' => 'AC',
            'pausado' => false,
            'fk_usuario_id' => 3,
        ]);

        vagasModel::create([
            'id_vagas' => 34,
            'email_vaga' => 'ana.costa@example.com',
            'titulo_vagas' => 'Desenvolvedor Frontend Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9000,
            'fim_salario_vagas' => 11500,
            'local_vagas' => 'Rio de Janeiro - RJ',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'TS',
            'estado_vaga' => 'RJ',
            'pausado' => false,
            'fk_usuario_id' => 4,
        ]);

        vagasModel::create([
            'id_vagas' => 35,
            'email_vaga' => 'lucas.souza@example.com',
            'titulo_vagas' => 'Desenvolvedor Backend Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 13000,
            'fim_salario_vagas' => 16000,
            'local_vagas' => 'Belo Horizonte - MG',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'GO',
            'estado_vaga' => 'MG',
            'pausado' => false,
            'fk_usuario_id' => 5,
        ]);
        vagasModel::create([
            'id_vagas' => 36,
            'email_vaga' => 'beatriz.lima@example.com',
            'titulo_vagas' => 'Desenvolvedor React Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 5500,
            'fim_salario_vagas' => 7000,
            'local_vagas' => 'Salvador - BA',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'JS',
            'estado_vaga' => 'BA',
            'pausado' => false,
            'fk_usuario_id' => 6,
        ]);

        vagasModel::create([
            'id_vagas' => 37,
            'email_vaga' => 'pedro.rocha@example.com',
            'titulo_vagas' => 'DevOps Engineer Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 14000,
            'fim_salario_vagas' => 17000,
            'local_vagas' => 'São Paulo - SP',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'DEVOPS',
            'estado_vaga' => 'SP',
            'pausado' => false,
            'fk_usuario_id' => 7,
        ]);

        vagasModel::create([
            'id_vagas' => 38,
            'email_vaga' => 'clara.martins@example.com',
            'titulo_vagas' => 'Desenvolvedor Fullstack Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9000,
            'fim_salario_vagas' => 12000,
            'local_vagas' => 'Recife - PE',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'PHP',
            'estado_vaga' => 'PE',
            'pausado' => false,
            'fk_usuario_id' => 8,
        ]);

        vagasModel::create([
            'id_vagas' => 39,
            'email_vaga' => 'gustavo.alves@example.com',
            'titulo_vagas' => 'Desenvolvedor Python Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 13000,
            'fim_salario_vagas' => 16000,
            'local_vagas' => 'Natal - RN',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'PY',
            'estado_vaga' => 'RN',
            'pausado' => false,
            'fk_usuario_id' => 9,
        ]);

        vagasModel::create([
            'id_vagas' => 40,
            'email_vaga' => 'fernanda.souza@example.com',
            'titulo_vagas' => 'Engenheiro de Machine Learning Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 11000,
            'fim_salario_vagas' => 14000,
            'local_vagas' => 'Belo Horizonte - MG',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'ML',
            'estado_vaga' => 'MG',
            'pausado' => false,
            'fk_usuario_id' => 10,
        ]);

        vagasModel::create([
            'id_vagas' => 41,   
            'email_vaga' => 'rafael.ferreira@example.com',
            'titulo_vagas' => 'Desenvolvedor PHP Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 5000,
            'fim_salario_vagas' => 6500,
            'local_vagas' => 'Brasília - DF',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'PHP',
            'estado_vaga' => 'DF',
            'pausado' => false,
            'fk_usuario_id' => 11,
        ]);

        vagasModel::create([
            'id_vagas' => 42,  
            'email_vaga' => 'carla.santos@example.com',
            'titulo_vagas' => 'Engenheiro de Software Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9000,
            'fim_salario_vagas' => 12000,
            'local_vagas' => 'Curitiba - PR',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'CS',
            'estado_vaga' => 'PR',
            'pausado' => false,
            'fk_usuario_id' => 12,
        ]);

        vagasModel::create([
            'id_vagas' => 43,
            'email_vaga' => 'diego.oliveira@example.com',
            'titulo_vagas' => 'Desenvolvedor Kotlin Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 13000,
            'fim_salario_vagas' => 15000,
            'local_vagas' => 'Maceió - AL',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'KT',
            'estado_vaga' => 'AL',
            'pausado' => false,
            'fk_usuario_id' => 13,
        ]);

        vagasModel::create([
            'id_vagas' => 44, 
            'email_vaga' => 'fernanda.costa@example.com',
            'titulo_vagas' => 'Desenvolvedor SQL Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 4800,
            'fim_salario_vagas' => 6200,
            'local_vagas' => 'Goiânia - GO',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'SQL',
            'estado_vaga' => 'GO',
            'pausado' => false,
            'fk_usuario_id' => 14,
        ]);

        vagasModel::create([
            'id_vagas' => 45,
            'email_vaga' => 'juliana.lima@example.com',
            'titulo_vagas' => 'Desenvolvedor C Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 14000,
            'fim_salario_vagas' => 17000,
            'local_vagas' => 'São Luís - MA',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'C',
            'estado_vaga' => 'MA',
            'pausado' => false,
            'fk_usuario_id' => 15,
        ]);
        vagasModel::create([
            'id_vagas' => 46,  
            'email_vaga' => 'gabriel.souza@example.com',
            'titulo_vagas' => 'Desenvolvedor Java Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9000,
            'fim_salario_vagas' => 11000,
            'local_vagas' => 'Campinas - SP',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'JV',
            'estado_vaga' => 'SP',
            'pausado' => false,
            'fk_usuario_id' => 16,
        ]);

        vagasModel::create([
            'id_vagas' => 47,
            'email_vaga' => 'lucas.oliveira@example.com',
            'titulo_vagas' => 'Desenvolvedor Ruby Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 6000,
            'fim_salario_vagas' => 7500,
            'local_vagas' => 'Florianópolis - SC',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'RB',
            'estado_vaga' => 'SC',
            'pausado' => false,
            'fk_usuario_id' => 17,
        ]);

        vagasModel::create([
            'id_vagas' => 48,
            'email_vaga' => 'renata.almeida@example.com',
            'titulo_vagas' => 'Desenvolvedor Go Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 10500,
            'fim_salario_vagas' => 13000,
            'local_vagas' => 'Fortaleza - CE',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'GO',
            'estado_vaga' => 'CE',
            'pausado' => false,
            'fk_usuario_id' => 18,
        ]);

        vagasModel::create([
            'id_vagas' => 49,
            'email_vaga' => 'marcos.teixeira@example.com',
            'titulo_vagas' => 'Engenheiro de Dados Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 15000,
            'fim_salario_vagas' => 18000,
            'local_vagas' => 'Porto Alegre - RS',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'PY',
            'estado_vaga' => 'RS',
            'pausado' => false,
            'fk_usuario_id' => 19,
        ]);

        vagasModel::create([
            'id_vagas' => 50, 
            'email_vaga' => 'paula.goncalves@example.com',
            'titulo_vagas' => 'Desenvolvedor Rust Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 11000,
            'fim_salario_vagas' => 13000,
            'local_vagas' => 'Manaus - AM',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'RS',
            'estado_vaga' => 'AM',
            'pausado' => false,
            'fk_usuario_id' => 20,
        ]);

        vagasModel::create([
            'id_vagas' => 51,
            'email_vaga' => 'thiago.andrade@example.com',
            'titulo_vagas' => 'Desenvolvedor Frontend Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 5000,
            'fim_salario_vagas' => 7000,
            'local_vagas' => 'Vitória - ES',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'PRE',
            'ferramenta_vaga' => 'JS',
            'estado_vaga' => 'ES',
            'pausado' => false,
            'fk_usuario_id' => 21,
        ]);

        vagasModel::create([
            'id_vagas' => 52,
            'email_vaga' => 'amanda.martins@example.com',
            'titulo_vagas' => 'Desenvolvedor .NET Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 9500,
            'fim_salario_vagas' => 12000,
            'local_vagas' => 'Ribeirão Preto - SP',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'CS',
            'estado_vaga' => 'SP',
            'pausado' => false,
            'fk_usuario_id' => 22,
        ]);

        vagasModel::create([
            'id_vagas' => 53,
            'email_vaga' => 'carlos.lima@example.com',
            'titulo_vagas' => 'Desenvolvedor C++ Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 14500,
            'fim_salario_vagas' => 17000,
            'local_vagas' => 'Curitiba - PR',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'CPP',
            'estado_vaga' => 'PR',
            'pausado' => false,
            'fk_usuario_id' => 23,
        ]);

        vagasModel::create([
            'id_vagas' => 54,
            'email_vaga' => 'lara.souza@example.com',
            'titulo_vagas' => 'Engenheiro de Software swift Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 14000,
            'fim_salario_vagas' => 17000,
            'local_vagas' => 'Rio de Janeiro - RJ',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'SW',
            'estado_vaga' => 'RJ',
            'pausado' => false,
            'fk_usuario_id' => 24,
        ]);

        vagasModel::create([
            'id_vagas' => 55,
            'email_vaga' => 'bruno.nascimento@example.com',
            'titulo_vagas' => 'Desenvolvedor Scala Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 12000,
            'fim_salario_vagas' => 14000,
            'local_vagas' => 'Recife - PE',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'SC',
            'estado_vaga' => 'PE',
            'pausado' => false,
            'fk_usuario_id' => 25,
        ]);

        vagasModel::create([
            'id_vagas' => 56,
            'email_vaga' => 'juliana.cardoso@example.com',
            'titulo_vagas' => 'Desenvolvedor TypeScript Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 6000,
            'fim_salario_vagas' => 7500,
            'local_vagas' => 'Belém - PA',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'TS',
            'estado_vaga' => 'PA',
            'pausado' => false,
            'fk_usuario_id' => 26,
        ]);

        vagasModel::create([
            'id_vagas' => 57,
            'email_vaga' => 'rodrigo.ferreira@example.com',
            'titulo_vagas' => 'Engenheiro de Dados Sênior',
            'descrição' => "null",
            'inicio_salario_vagas' => 16000,
            'fim_salario_vagas' => 18000,
            'local_vagas' => 'Fortaleza - CE',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'SQL',
            'estado_vaga' => 'CE',
            'pausado' => false,
            'fk_usuario_id' => 27,
        ]);

        vagasModel::create([
            'id_vagas' => 58,
            'email_vaga' => 'mariana.gomes@example.com',
            'titulo_vagas' => 'Desenvolvedor Rust Pleno',
            'descrição' => "null",
            'inicio_salario_vagas' => 12000,
            'fim_salario_vagas' => 13000,
            'local_vagas' => 'Salvador - BA',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'P',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'RS',
            'estado_vaga' => 'BA',
            'pausado' => false,
            'fk_usuario_id' => 28,
        ]);

        vagasModel::create([
            'id_vagas' => 59,
            'email_vaga' => 'felipe.azevedo@example.com',
            'titulo_vagas' => 'Desenvolvedor Frontend Júnior',
            'descrição' => "null",
            'inicio_salario_vagas' => 5000,
            'fim_salario_vagas' => 7000,
            'local_vagas' => 'Porto Alegre - RS',
            'tipo_vaga' => 'CLT',
            'senioridade_vagas' => 'J',
            'scala_vagas' => 'RE',
            'ferramenta_vaga' => 'JS',
            'estado_vaga' => 'RS',
            'pausado' => false,
            'fk_usuario_id' => 29,
        ]);

        vagasModel::create([
            'id_vagas' => 60,
            'email_vaga' => 'vanessa.moura@example.com',
            'titulo_vagas' => 'Desenvolvedor Java Senior',
            'descrição' => "null",
            'inicio_salario_vagas' => 17000,
            'fim_salario_vagas' => 19000,
            'local_vagas' => 'São Paulo - SP',
            'tipo_vaga' => 'PJ',
            'senioridade_vagas' => 'S',
            'scala_vagas' => 'HI',
            'ferramenta_vaga' => 'JV',
            'estado_vaga' => 'SP',
            'pausado' => false,
            'fk_usuario_id' => 30,
        ]);
    }
}
